import { useState, useEffect } from 'react'
import Head from 'next/head'
import AppLayout from 'components/AppLayout'
import Button from 'components/Button'
import Github from 'components/Icons/Github'
import Avatar from 'components/Avatar/index'
import { loginWithGithub, onAuthStateChanged } from '../firebase/client'
import { colors } from '../styles/theme'

export default function Home() {
  const [user, setUser] = useState(undefined)
  useEffect(() => {
    onAuthStateChanged(setUser)
  }, [])

  const onHandleLogin = () => {
    loginWithGithub().then(setUser)
  }

  return (
    <>
      <Head>
        <title>Twitter Clon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/logo.png" alt="TweetDev" />
          <h1>TweetDev</h1>
          <h2>
            Talk about development
            <br />
            with developers 👨‍💻👩‍💻
          </h2>
          <div>
            {user === null && (
              <Button onClick={onHandleLogin}>
                <Github fill={colors.white} />
                Login with Github
              </Button>
            )}
            {user && user.username && user.avatar && (
              <Avatar
                src={user.avatar}
                alt={user.username}
                withLbl={true}
                lbl={user.username}
              />
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        section {
          height: 100%;
          display: grid;
          place-content: center;
          place-items: center;
        }
        img {
          width: 120px;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 16;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 18px;
          margin: 0px;
        }
        div {
          width: 100%;
          margin-top: 24px;
        }
      `}</style>
    </>
  )
}
