import Head from 'next/head'
import AppLayout from '../components/appLayout/AppLayout'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
				<h1>
					<a href="https://nextjs.org">TwetDev</a>
				</h1>
      </AppLayout>

			<style jsx>{`
				
			`}</style>
    </>
  )
}
